### ISSUE TITLE
Some problems with values

### ISSUE THREAD

**Issue by Metrakit** [zurb/pizza#22]
Hi,

I found the last weekend your wonderful library and have created my own AngularJS directice with this one but I found some mistakes when the values are displayed on the chart. 
You can see on the pic : 

![graph](https://cloud.githubusercontent.com/assets/3305600/3255340/28adf792-f209-11e3-88f3-294cd831b572.jpg)

The data-values dont correspond to the values displayes on the chart.

And it's the same on your official website :

![graph2](https://cloud.githubusercontent.com/assets/3305600/3255341/28b4c572-f209-11e3-9cc5-91989b973801.png)

Cordially, Metrakit.

**Comment by mattjohnlee** [comment]
I'm experiencing the same issue, where the values on the bar chart's y-axis don't match the data-values in my ul. If you'll review the attached screenshot, you'll see that while my chart values go up to 245.4, the highest value rendered on the y-axis is 200.

![screen shot 2015-06-12 at 9 43 43 am](https://cloud.githubusercontent.com/assets/9064594/8131352/c15be17c-10e7-11e5-91ba-58099e3869d2.png)
